spring.application.name=uptime-monitor-api

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/uptime_monitor}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:uptime}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:uptime}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info
